Traceback (most recent call last):
  File "C:\Users\Zulfa\miniconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\Zulfa\miniconda3\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\Zulfa\miniconda3\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\Zulfa\miniconda3\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\Zulfa\miniconda3\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\Zulfa\miniconda3\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\Zulfa\miniconda3\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\Zulfa\miniconda3\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Append the result (planet's name and index value) to a .txt file in the same folder 
with open('out.txt','w') as f:
    i = 1
    for a in habIndexWithName:
        if i == 3:
            print(a, file=f)
            i = 1
        else:
            print(a, file=f, end="")
            i += 1
------------------

[1;31m-----------------------------------------------------------------------[0m
[1;31mNameError[0m                             Traceback (most recent call last)
Input [1;32mIn [1][0m, in [0;36m<cell line: 2>[1;34m()[0m
[0;32m      2[0m [38;5;28;01mwith[39;00m [38;5;28mopen[39m([38;5;124m'[39m[38;5;124mout.txt[39m[38;5;124m'[39m,[38;5;124m'[39m[38;5;124mw[39m[38;5;124m'[39m) [38;5;28;01mas[39;00m f:
[0;32m      3[0m     i [38;5;241m=[39m [38;5;241m1[39m
[1;32m----> 4[0m     [38;5;28;01mfor[39;00m a [38;5;129;01min[39;00m [43mhabIndexWithName[49m:
[0;32m      5[0m         [38;5;28;01mif[39;00m i [38;5;241m==[39m [38;5;241m3[39m:
[0;32m      6[0m             [38;5;28mprint[39m(a, file[38;5;241m=[39mf)

[1;31mNameError[0m: name 'habIndexWithName' is not defined
NameError: name 'habIndexWithName' is not defined

